#define F_charheight 1
#define F_charwidth 2
#define F_gfx_BGcolour -146
#define F_gfx_ChangeColour -66
#define F_gfx_Circle -51
#define F_gfx_CircleFilled -52
#define F_gfx_Clipping -148
#define F_gfx_ClipWindow -65
#define F_gfx_Cls -41
#define F_gfx_Contrast -154
#define F_gfx_FrameDelay -151
#define F_gfx_GetPixel -54
#define F_gfx_Line -46
#define F_gfx_LinePattern -155
#define F_gfx_LineTo -44
#define F_gfx_MoveTo -42
#define F_gfx_Orbit 3
#define F_gfx_OutlineColour -153
#define F_gfx_Polygon 4
#define F_gfx_Polyline 5
#define F_gfx_PutPixel -53
#define F_gfx_Rectangle -49
#define F_gfx_RectangleFilled -50
#define F_gfx_ScreenMode -152
#define F_gfx_Set -40
#define F_gfx_SetClipRegion -68
#define F_gfx_Transparency -150
#define F_gfx_TransparentColour -149
#define F_gfx_Triangle -55
#define F_media_Flush -78
#define F_media_Image -77
#define F_media_Init -79
#define F_media_ReadByte -73
#define F_media_ReadWord -74
#define F_media_SetAdd -71
#define F_media_SetSector -72
#define F_media_Video -69
#define F_media_VideoFrame -70
#define F_media_WriteByte -75
#define F_media_WriteWord -76
#define F_putCH -2
#define F_putstr 6
#define F_txt_Attributes -142
#define F_txt_BGcolour -130
#define F_txt_Bold -138
#define F_txt_FGcolour -129
#define F_txt_FontID -131
#define F_txt_Height -133
#define F_txt_Inverse -140
#define F_txt_Italic -139
#define F_txt_MoveCursor -28
#define F_txt_Opacity -137
#define F_txt_Set -29
#define F_txt_Underline -141
#define F_txt_Width -132
#define F_txt_Xgap -134
#define F_txt_Ygap -135
#define F_BeeP -38
#define F_sys_GetModel 7
#define F_sys_GetVersion 8
#define F_sys_GetPmmC 9
#define F_blitComtoDisplay 10
#define F_setbaudWait 11
#define F_peekW -11
#define F_pokeW -13
#define F_peekB -10
#define F_pokeB -12
#define F_joystick -39
#define F_SSTimeout 12
#define F_SSSpeed 13
#define F_SSMode 14
